spring.datasource.url=${DB_URL:jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres}
spring.datasource.username=${DB_USERNAME:postgres.ilmxqxewpgxnlgypkkyq}
spring.datasource.password=${DB_PASSWORD:Sonlybanhbon1@}
spring.datasource.driver-class-name=org.postgresql.Driver

# Explicitly set dialect to avoid metadata detection issues
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
